version: "2"
services:
  broker:
    build: broker
    command: npm run dev
    volumes:
      - ./broker:/usr/src/app/
    ports:
      - "8000:8000"
  frontend:
    build: frontend
    command: npm start
    volumes:
      - ./frontend:/app/
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true