version: "3.4"
services:
  broker:
    build:
      context: ./broker
      network: host
    command: npm run dev
    volumes:
      - ./broker:/usr/src/app/
    ports:
      - "8000:8000"
  frontend:
    build: frontend
    command: npm start
    volumes:
      - ./frontend:/app/
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  predictor:
    build:
      context: ./predictor
      network: host
    volumes:
      - ./predictor/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
  modelator_d3_rw:
    build:
      context: ./modelator_d3_rw
      network: host
    volumes:
      - ./modelator_d3_rw/:/usr/src/app/
    ports:
      - 6001:6001
    environment:
      PORT: 6001
      FLASK_DEBUG: 1